baseurl = "https://daisuke.co/"
languageCode = "ja-jp"
title = "Era Skeh dai"
theme = "nofancy"

#if not set copyright, default copyright template will be applied
copyright = "Copyright (c) 2017 - 2018, Daisuke Osada (daiskeh); all rights reserved."

[params]
    highlight="Assign a syntax highlight style"

[author]
    name = "daiskeh"
    github = "dai"
    linkedin = "osada"
    facebook = "daiskeh"
    gaID = ""
    twitter = "daisuke"
